export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const LOGIN_FAIL = 'LOGIN_FAIL';

